### ISSUE TITLE
Regarding bulk conversation 

### ISSUE THREAD

**Issue by bunnysayzz** [ParitoshPky/pdisk_uploader#15]
Bro bro, its working fine. But can you plz update your code so that it can convert bulk pdisk link. Like in one post 10-15 links at once. I tried but failed sadly. Plz plzz do this for me. Thanks

**Comment by ParitoshPky** [comment]
> Bro bro, its working fine. But can you plz update your code so that it can convert bulk pdisk link. Like in one post 10-15 links at once. I tried but failed sadly. Plz plzz do this for me. Thanks

can you just send me post on telegram so that i can check it 
others all bulk conversion working fine

**Comment by ParitoshPky** [comment]
> > Bro bro, its working fine. But can you plz update your code so that it can convert bulk pdisk link. Like in one post 10-15 links at once. I tried but failed sadly. Plz plzz do this for me. Thanks
> 
> can you just send me post on telegram so that i can check it others all bulk conversion working fine

t.me/paritoshpky
