### ISSUE TITLE
Concanate str erro

### ISSUE THREAD

**Issue by amitsharma791996** [ParitoshPky/pdisk_uploader#4]
Sir i am uisng repo for my bot .
But when giving a dl to it its giving error
"Error: can only concatenate str (not "NoneType") to str "

Please guide sir

**Comment by ParitoshPky** [comment]
please give me error screenshot 
also the heroku logs screenshot so that i can help you easily

**Comment by amitsharma791996** [comment]
> please give me error screenshot also the heroku logs screenshot so that i can help you easily

Can u shre ur tele id so that i cn contct u plz ?

**Comment by ParitoshPky** [comment]
> > please give me error screenshot also the heroku logs screenshot so that i can help you easily
> 
> Can u shre ur tele id so that i cn contct u plz ?

@paritoshpky

**Comment by ParitoshPky** [comment]
due to no response closing this issue...
still you can contact me on telegram.
