### ISSUE TITLE
pdisk blocked API uploads

### ISSUE THREAD

**Issue by sunilroyy007** [ParitoshPky/pdisk_uploader#6]
i think you should try deploy bot first and use. Pdisk wont allow people to upload using API from bots. And yah i tried it it wont upload

**Comment by ParitoshPky** [comment]
> i think you should try deploy bot first and use. Pdisk wont allow people to upload using API from bots. And yah i tried it it wont upload

bro i have deployed and checked and many people sending thanks on my telegram...
so better check once please...
must use your own pdisk_ap_key

**Comment by sunilroyy007** [comment]
> > i think you should try deploy bot first and use. Pdisk wont allow people to upload using API from bots. And yah i tried it it wont upload
> 
> bro i have deployed and checked and many people sending thanks on my telegram... so better check once please... must use your own pdisk_api_key

bro i am using my own api and key and i have pasted link in bot several times it always says invalid. i tried same link via website and it uploads perfectly
stop closing issues bruh argue or explain if people are wrong and when issue solved then close it

**Comment by ParitoshPky** [comment]
> > > i think you should try deploy bot first and use. Pdisk wont allow people to upload using API from bots. And yah i tried it it wont upload
> > 
> > 
> > bro i have deployed and checked and many people sending thanks on my telegram... so better check once please... must use your own pdisk_api_key
> 
> bro i am using my own api and key and i have pasted link in bot several times it always says invalid. i tried same link via website and it uploads perfectly stop closing issues bruh argue or explain if people are wrong and when issue solved then close it

screenshot please both both & heroku log

**Comment by ParitoshPky** [comment]
> > > i think you should try deploy bot first and use. Pdisk wont allow people to upload using API from bots. And yah i tried it it wont upload
> > 
> > 
> > bro i have deployed and checked and many people sending thanks on my telegram... so better check once please... must use your own pdisk_api_key
> 
> bro i am using my own api and key and i have pasted link in bot several times it always says invalid. i tried same link via website and it uploads perfectly stop closing issues bruh argue or explain if people are wrong and when issue solved then close it

bro i thought

**Comment by sunilroyy007** [comment]
> > > > i think you should try deploy bot first and use. Pdisk wont allow people to upload using API from bots. And yah i tried it it wont upload
> > > 
> > > 
> > > bro i have deployed and checked and many people sending thanks on my telegram... so better check once please... must use your own pdisk_api_key
> > 
> > 
> > bro i am using my own api and key and i have pasted link in bot several times it always says invalid. i tried same link via website and it uploads perfectly stop closing issues bruh argue or explain if people are wrong and when issue solved then close it
> 
> screenshot please both bot & heroku log

ok 2 minutes

**Comment by ParitoshPky** [comment]
> i think you should try deploy bot first and use. Pdisk wont allow people to upload using API from bots. And yah i tried it it wont upload

actually you are not sure about what you are saying thats why i closed this issue..
everyone using and you are saying this type of statement...

**Comment by sunilroyy007** [comment]
> > i think you should try deploy bot first and use. Pdisk wont allow people to upload using API from bots. And yah i tried it it wont upload
> 
> actually you are not sure about what you are saying thats why i closed this issue.. everyone using and you are saying this type of statement...

i agree my approach was wrong. it sounds like attack but i just wanna report. i will contact you in Telegram will show logs and screenshot

**Comment by ParitoshPky** [comment]
> > > i think you should try deploy bot first and use. Pdisk wont allow people to upload using API from bots. And yah i tried it it wont upload
> > 
> > 
> > actually you are not sure about what you are saying thats why i closed this issue.. everyone using and you are saying this type of statement...
> 
> i agree my approach was wrong. it sounds like attack but i just wanna report. i will contact you in Telegram will show logs and screenshot

it's ok i am there..

**Comment by sunilroyy007** [comment]
actually what happened is it doesn't upload before maybe because high pdisk server , now its working verry good. incase if anyone's doesn't upload or says invalid this is the cause. 

this repo works perfectly

**Comment by ParitoshPky** [comment]
> actually what happened is it doesn't upload before maybe because high pdisk server , now its working verry good. incase if anyone's doesn't upload or says invalid this is the cause.
> 
> this repo works perfectly

thanks for your appreciation
